spring.datasource.url=jdbc:postgresql://localhost:5432/todotask_db
spring.jpa.hibernate.ddl-auto=update

logging.level.root=DEBUG
logging.level.com.todotask=DEBUG
logging.level.org.springframework=DEBUG
